### PR TITLE
Add Keep Screen On Action Bar Item

### LINKED ISSUE #58: Action bar item to keep screen on
Currently the screen is kept on on the timer page. An item in the action bar would be useful that toggles "keep screen on".

On the timer page this setting should be locked and always turned on.

### PR DESCRIPTION
**Pull request by theAkito**
Resolves #58.

### CODE REVIEW

**Comment by mueller-ma** [comment]
Can you move the implementation to the AbstractBaseFragment? One preference for all fragments is probably better to maintain.

**Comment by theAkito** [comment]
> Can you move the implementation to the AbstractBaseFragment?

Like the entire Menu Provider? I have created a distinct menu for each Fragment, in case future items will be added.

I'm also not sure how to make use of the Fragment Binding in the abstract class.

> One preference for all fragments is probably better to maintain.

I thought, it'd be helpful if the user could decide for each Fragment. At least, I would expect that changing the setting in one Fragment wouldn't change the behaviour in another one. If we are going to change it for all fragments (except Buzzer & Timer), then it should be a general setting, anyway.

**Comment by mueller-ma** [comment]
> Like the entire Menu Provider? I have created a distinct menu for each Fragment, in case future items will be added.

You can have multiple MenuProviders, so one for all fragments (keep screen on) and one for each fragment, if required.

> I'm also not sure how to make use of the Fragment Binding in the abstract class.

In base class:
````kotlin
abstract fun getViewForKeepScreenOn: View
````

And override with the specific view, e.g.:
````kotlin
override fun getViewForKeepScreenOn = binding.randomScrollView
````

> I thought, it'd be helpful if the user could decide for each Fragment. At least, I would expect that changing the setting in one Fragment wouldn't change the behaviour in another one. If we are going to change it for all fragments (except Buzzer & Timer), then it should be a general setting, anyway.

IMO it's better to maintain (less nearly duplicate code) to have only one preference. As a user I'd also expect that this settings toggle "keep alive" in all fragments.

**Comment by theAkito** [comment]
@mueller-ma

Please, review.

**Comment by mueller-ma** [comment]
You can ignore the CodeFactor issue. It doesn't come from this PR.

As an icon can you use two "brightness" icons from https://materialdesignicons.com/ ?

**Comment by mueller-ma** [comment]
Did you check if the icon is visible in dark mode?

**Comment by theAkito** [comment]
> You can ignore the CodeFactor issue. It doesn't come from this PR.

I know, else I would've fixed it already. 😃



> Did you check if the icon is visible in dark mode?

The icons I chose are visible in dark mode.





> As an icon can you use two "brightness" icons from https://materialdesignicons.com/ ?

They look weird, but I'll check them out.

**Comment by mueller-ma** [comment]
Thanks!

**Pull request merged**
