### PR TITLE
Issue: #64 Added custom audio tone for timer finished

### PR DESCRIPTION
**Pull request by Kardelio**
#64 Issue dealt with

Added this audio file (https://soundbible.com/529-Pager-Beeps.html) from soundbible.com as a `raw` file into the codebase.
Also switched the timer fragment's timer finished sound to play this audio and added credits on ReadMe

### CODE REVIEW

**Comment by mueller-ma** [comment]
Can you check if it's possible to play this sound even if the device is set to DND or media volume is at 0?

**Comment by mueller-ma** [comment]
I found a way and pushed it to your branch.

**Comment by mueller-ma** [comment]
The build error is caused by translations, don't mind about that.

**Comment by Kardelio** [comment]
@mueller-ma sorry only just seeing this!
Awesome looks like you solved it!

Cool you said you pushed it to my branch, so do I need to do anything then or is this PR still ok?

**Comment by mueller-ma** [comment]
This PR should be fine, but I want to fix the Crowdin integration first before merging this.

**Pull request merged**
