### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by EVOTk**
French translation except for "buzzers" which I don't know how to translate. What is it for?
On my phone, pressing "Player A" activates the box, which deactivates after a few seconds, but there is no sound or vibration.

### CODE REVIEW

**Comment by mueller-ma** [comment]
> What is it for?

It's for e.g. a quiz game where it matters if person A or B first pressed the buzzer. I can add a sound and vibration there.

**Comment by EVOTk** [comment]
Thank you for the answer. 
It can simply be translated as "Buzzer" then. I am not a quiz game player, I did not make the connection :)

**Comment by mueller-ma** [comment]
Thanks!

**Comment by EVOTk** [comment]
Thanks to you for this app :)

**Pull request merged**
